### ISSUE TITLE
TaskLogic-Trial Initiation grabbing more data than normal

### ISSUE THREAD

**Issue by ygrayson** [SainsburyWellcomeCentre/aeon_mecha#176] opened 2022-11-29 09:29 UTC
On the [gl-octagon-dataset](https://github.com/SainsburyWellcomeCentre/aeon_mecha/tree/gl-octagon-dataset) branch, I tried to read Trial Initiation timestamps with the following code. 
`root = #data-root-here`
`sessions = api.load(root, Chunk(octagon01.Metadata))`
`sessiondata = partial(api.load, root, epoch='2022-11-10T16-28-21')`
`trial_initiation = sessiondata(octagon01.TaskLogic.TrialInitiation)`

The resulting timestamps were more than I expected. Originally Trial Initiation timestamps should be the ones in the HARP files with TaskLogic_1_ format, but many more HARP bin files were also read.

The HARP file format definition code is in `/aeon/schema/octagon.py`, line 77:
`return { "TrialInitiation": _reader.Harp(f"{pattern}_1", columns=['trial_type']) }`
But this will also read TaskLogic_10_, TaskLogic_11_, TaskLogic_12_, etc. This line should be changed to:
`return { "TrialInitiation": _reader.Harp(f"{pattern}_1_", columns=['trial_type']) }`

Hope this helps.

**Comment by glopesdev** [comment] 2022-11-29 10:43
@ygrayson this seems related to #145 which we had identified earlier. We are preparing a fix to discuss tomorrow at DA meeting which if merged would likely resolve this.

**Comment by glopesdev** [comment] 2022-11-29 10:45
Duplicate of #145

**Closed** 2022-11-29 10:46 UTC
